language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: GgsJPfXlyoSDF0rnExi3sQ6kc3fiZTZm+KOVlWV5ZIYZXebsbhwU+rZ1MrSZcqQ3nTeVLfLRE5e4m/4QuuzyszLHuE4UtnkI68Za2OaXdFwLp0r61v2btCGqSImCtipGv9x9RHs9ssB6CREpgK8RB95cfr6Rhk49Q86VsH9WoBAaPDvn6UM+eMGDBJPd4d7V7an9it/AdSKKz042p582A8r9KDRfd98KVOWzgVvRxqo7vYpx5J5H2oFAC1wI19gt0fKcm6wBa6JwxZxGN+vM3CqSNXx0tQmGVz8jV0qEn8FY9s/5kNcczZkWbpf58JSEgiWn4u1z1YDvfYHzTx8MkwWVFW13Oa2XacoSFAstLPXMyZiVWJdRbMUmP5IEIO1dRxXBUG5E163525NPtBx+raQ/79tqy3dmvj7X9wXMmtlYd/6qxggiU+mrP05Keko/YFNrjE4n3lkkH6kt5Y9yqvZDf/xMDGhsqFUhnlR8UH9TVRuY9N/03MKQmZ46lwMwfni0ph41gnFbDXOIksbNTmREA6CQ6eT9ZMyEpdHjjyJ4lU9A4wY50lXb2Tgtrg35ZYj38wlC+7bOz1tWx4kgsgz7LJoaF/bPIVS4Xgp7YkGqK3ls2WAytfX1DCkfJcWbPhguOEzp42O83uKVCZaQM13v9LMkS/ZYAIJHt+H8f4s=
  app: zh47
  on:
    repo: avrj/slack-clone
script:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
after_success:
- codecov
env:
  global:
  - NODE_ENV=test
  - secure: AvJEVP7w1y3hLhuWxFbkoUjNHhfe6h2fH5k99j67TyQZXTSCoWMZ+DFhjap1UZIOHPIcN6XcdVj40uc6yMJvE2xkAQXZTodW5qVgqiQTEk9iqgQK1dfn5OuMiMIh0jcWa0B5X1GmgjqW6YjURjG0EUWQTW49ENjeCuOQjdVu4NNKwDdW+PnlWjhX9dYPCn32b1WBQWxSvqgPbmfzyyAcQvdbiCYs6ZNCQYXHERrjV8Cagb+jbYlDlY3oyJI/t19xlEL6oFudypv1F/1CvBvOp+/HrwfxknSgvgybNDTjlTyHLPNv1w2CHLBUqgaFwT5s9mQnj/lryB4kzljTtbEj3BByZP6GFcBW8yUZwLkEuld/1M0ImYDkMyof5MLVxn8KIc5KHR0bg40sgytXnzN4rlSsRlCylQqkCyj2ieTSQ9YRR+ppHSnsybb6s7QHg0aFmFWrr8NZSYNo8YZzaIHd9QwZ9fFJg1JVX2CBIr/LvKGlJBWMblyJ6v5Epp21cD3K6+b3c2CFym7+Go6sNOeOOhfA7BOmIf1Z5vn6kdw9ZrtGR+oI8N0p4jQDmXwR6iiG9JYpFP6Qc3PlAPc9yHjnu/A/kC2u7qjUe3m3KAKrYQ6PD7nC9toykDNl8z+4BalBnRkphR2DTwoNBOHAfhKsGGS+dWncoithqKi0Ha8bJzQ=
